### PR TITLE
Continuous build on Linux, Windows, MacOS

### PR DESCRIPTION
**Pull request by xanderdin**
Hey guys, it looks like there's a demand for fresh continuous builds of LibreCAD and AppImage packages (#858). Here's my solution (if you don't mind connecting [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) to the project). It shouldn't affect current TravisCI configuration and can be run in parallel.

Azure Pipelines docs are [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fpipelines%2Fbreadcrumb%2Ftoc.json&view=azure-devops). It is free for open source projects and provides quite enough resources and a bunch of features. I experimented a little bit with those and created configuration for LibreCAD.

### What it does:

On every change of master branch a parallel build is triggered for Linux, Windows and MacOS. After successful build there will be packages for those OSes available for download:

**AppImage** -- for Linux
**7z archive** -- for Windows (I failed to create windows installer so far)
**DMG package** -- for MacOS.

My experimental pipeline from this configuration is available [here](https://dev.azure.com/xanderdin/PlayWithAzure/_build?definitionId=1). 
You can navigate to the [last successful build](https://dev.azure.com/xanderdin/PlayWithAzure/_build/results?buildId=121) and see and download built packages by pressing **Artifacts** button.

I tested generated AppImage on Debian, Ubuntu, openSUSE, Fedora. All work fine.
I didn't test packages for Windows and MacOS because I haven't those OSes at my disposition.

Generated AppImage also fully supports running console tools (ttf2lff, dxf2pdf).

### CODE REVIEW

**Comment by wrgrant** [comment]
Agreed package builds for each commit would be nice.

What about using the native [Github Actions](https://github.com/features/actions)?

I think it's a big win to bring as much as possible into the same platform. For collaborator ease of use. But also for better UX (less confusion) for users trying to find the packages. 

I could help with the Windows installer. Though I'm sure this exists somewhere already (hopefully it's created with a script).

**Comment by xanderdin** [comment]
This PR was made before Github Actions were announced. And now it already 'smells'. Also Windows build does not work anymore as it used to. Hopefully other builds still work as before.

I agree that now it seems more natural using Github Actions instead of Azure Pipelines, and I had thoughts on rewriting it. But these days I'm short on free time and probably won't be able to do it in the near future.

If you want to create something similar using Github Actions feel free to use my PR as a basis for your job.

**Comment by wrgrant** [comment]
Woah! Didn't even notice the timestamp. Things are moving along at a leisurely pace on this project :)

**Comment by DuncanLithgow** [comment]
yes, @wrgrant things do move slowly here. So this is just a ping to see if anyone is watching and has plans to get his working.

**Comment by lordofbikes** [comment]
This is done with GitHub Actions now, results are at https://github.com/LibreCAD/LibreCAD/releases/tag/latest.
Anyhow many thanks for your efforts :+1:

**Pull request closed without merging**
