### PR TITLE
DO NOT MERGE test commit for 2.0 Travis CI

### PR DESCRIPTION
**Pull request by lordofbikes**

### CODE REVIEW

**Comment by lordofbikes** [comment]
This pull request was accepted by Travis, but the 2.0 branch seems to be disabled meanwhile.
If required we can enable this again or I'll remove the files from 2.0 branch again.

We can control this in the [.travis.yml](https://github.com/LibreCAD/LibreCAD/blob/2.0/.travis.yml) as I pushed to 2.0 branch
```
branches:
  only:
    - master
    - 2.0
```
Travis log:
PR #693 accepted (branch not included or excluded)
  c80b574 - DO NOT MERGE test commit for 2.0 Travis CI
  received at: 2016-03-29 10:29:51

**Comment by maqifrnswa** [comment]
2.0 might need to be in quotes, and the .travis.yml in master doesn't say to only build master and 2.0, it might need to be changed if you want 2.0 to also build

**Comment by lordofbikes** [comment]
I'm aware of the diff with the master .travis.yml. After successfully testing the 2.0 .travis.yml I would have updated the master file. But then I found out that 2.0 must have been disabled in Travis CI settings.

I've checked the 2.0 .travis.yml with the online validation form and Travis CI said it's okay. But if you are sure about the branch quotes, I can add them before testing.

I advocate for building 2.0 too. I assume that we could make one or more stable 2.0.x releases until we finally release LibreCAD 2.1.0. At least we could fix the static analyzer errors.

**Comment by r-a-v-a-s** [comment]
I support releasing 2.0.10
if for no other reason than the memory leaks that were eliminated.
I'll make a change log.

2.1.0-beta is coming soon...ish :sunglasses:

**Comment by maqifrnswa** [comment]
@lordofbikes 2.0 without quotes is valid YAML, but I think it is interpreting it as a float instead of a string. It then can't find the float 2.0 branch since there only is a string 2.0 branch. I could be totally wrong - travis stuff is hard to do since it is sometimes a trial and error black box! I feel like i spam their build bots until I find the magic combination...

If 2.1 is released so, then this goes away - just wanted to share in case it can help someone. Outstanding job fixing all those warning and possible bugs! I'm trying to get 2.0.9 in Ubuntu xenial before it is released in a few days - some technical issues on their end, but if 2.0.10 is out soon I can push that one instead.

https://bugs.launchpad.net/ubuntu/+source/librecad/+bug/1558067

**Comment by lordofbikes** [comment]
I've added quotes to the 2.0 branch label, Travis CI online validation is still okay.

**Comment by lordofbikes** [comment]
My last push triggered a successful 2.0 build on Travis CI.
I've updated the master .travis.yml and added a 2.0 build status image to the master README.md.

I'll reset my fork repo and close this PR.

**Comment by r-a-v-a-s** [comment]
I just found these:

https://github.com/QupZilla/qupzilla/blob/master/.travis.yml
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt56-trusty

**Pull request closed without merging**
