### PR TITLE
use eigen replace boost

### PR DESCRIPTION
**Pull request by jacques-chen**
let  librecad more light. Boost lib is too weight

### CODE REVIEW

**Comment by dongxuli-concord-design** [comment]
Can we keep eigen as a dependency, instead keeping it in our codebase?

Currently, boost is only used to find the elliptical angle for a given arc length.

**Comment by jacques-chen** [comment]
yes ,you are right ,as a dependency is a good choice. but I had found another bug, I am try to fix it.&nbsp; use eigen replace boost, when i dimension well fail
&nbsp;

陈维晃
***@***.***
网址:&nbsp;www.whchen.net
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;www.OSLite.tech
电话: +86 13806897376



Jacques Chen&nbsp;
***@***.***
Site:&nbsp;www.whchen.net
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;www.OSLite.tech
Tel: +86 13806897376





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年7月4日(星期二) 晚上7:43
To: ***@***.***&gt;; 
Cc: "陈维晃/Jacques ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [LibreCAD/LibreCAD] use eigen replace boost (PR #1647)





 
Can we keep eigen as a dependency, instead keeping it in our codebase?
 
Currently, boost is only used to find the elliptical angle for a given arc length.

**Comment by lordofbikes** [comment]
This PR also removes JWW support and probably more.
Even when removing JWW was already considered lately, was this or the use of Eigen discussed before? Did I miss anything?

Also this PR has +267,954 −19,505 changes in one commit. This is a security nightmare.

And from a look at https://github.com/jacques-chen/LibreCAD-Mod I assume that this is still work in progress.

The proper way is to use separate branches for independent modifications (JWW, Boost, muparser) and make the changes transparent for review, by committing in reasonable steps.

**Comment by jacques-chen** [comment]
I will delete LibreCAD-Mod later, this is just a test project when i lean something about LC, it depend V2.2 .&nbsp;
I forgot write message about jww.In LC-MOD, i had delete jww boost and&nbsp;muparser,&nbsp; but just for test.
&nbsp;

陈维晃
***@***.***
网址:&nbsp;www.whchen.net
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;www.OSLite.tech
电话: +86 13806897376



Jacques Chen&nbsp;
***@***.***
Site:&nbsp;www.whchen.net
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;www.OSLite.tech
Tel: +86 13806897376





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: "Armin ***@***.***&gt;; 
Date: 2023年7月4日(星期二) 晚上8:00
To: ***@***.***&gt;; 
Cc: "陈维晃/Jacques ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [LibreCAD/LibreCAD] use eigen replace boost (PR #1647)





 
This PR also removes JWW support and probably more.
 Even when removing JWW was already considered lately, was this or the use of Eigen discussed before? Did I miss anything?
 
Also this PR has +267,954 −19,505 changes in one commit. This is a security nightmare.
 
And from a look at https://github.com/jacques-chen/LibreCAD-Mod I assume that this is still work in progress.
 
The proper way is to use separate branches for independent modifications (JWW, Boost, muparser) and make the changes transparent for review, by committing in reasonable steps.

**Comment by dxli** [comment]
To remove boost is good:

1, using c++ elliptical integrals instead of the boost version;
2, using newton raphson to find the elliptical angle for a given arc length;
3, using eigen matrices and vectors for qudratic forms;
4, using eigen polynomial equation solvers to replace our cubic/quartic solvers;
5, using pencils of ellipses to solver quadratic-quadratic equation sets.

**Comment by dxli** [comment]
I suggest a first step:
add eigen as a dependency, and include building support for MacOS and windows, but without removing boost.

If eigen dependency is added for all platforms, each usage of boost can be tweaked to use skim;

**Comment by lordofbikes** [comment]
The first step must be to check the Eigen licences.
Are they compatible with GPLv2?
Do they allow to keep source in LibreCAD repo? Possibly as `Git` submodule?
Are they valid for static or dynamic linking?

**Comment by dxli** [comment]
@lordofbikes eigen is under [MPL2](https://eigen.tuxfamily.org/index.php?title=Licensing_FAQ), which is much less restrictive than GPL licenses.

My understanding is that if we do not keep a copy of eigen in our codebase, we don't even have to mention it.

**Comment by jacques-chen** [comment]
this weekend i will try to add eigen as a dependency to replace boost and submit it



***@***.***
 
From: Dongxu Li
Date: 2023-07-06 11:05
To: LibreCAD/LibreCAD
CC: jacques-chen; Author
Subject: Re: [LibreCAD/LibreCAD] use eigen replace boost (PR #1647)
@lordofbikes eigen is under MPL2, which is much less restrictive than GPL licenses.
My understanding is that if we do not keep a copy of eigen in our codebase, we don't even have to mention it.

**Comment by dongxuli-concord-design** [comment]
Sounds great.

On the finding the inverse of elliptical integral,
I am not sure whether simple newton Raphson is robust enough. Can we use bisection followed by newton Raphson, to improve the robustness?

**Comment by lordofbikes** [comment]
> @lordofbikes eigen is under [MPL2](https://eigen.tuxfamily.org/index.php?title=Licensing_FAQ), which is much less restrictive than GPL licenses.

Just want to be sure, that this is considered and approved.
 
> My understanding is that if we do not keep a copy of eigen in our codebase, we don't even have to mention it.

This PR contains full Eigen source, that's why I mentioned it. I absolutely agree to not include the Eigen source in our repo.

The optimal implementation would use pre-processor macros, e.g.  `USE_BOOST` and `USE_EIGEN` or so to have the possibility to build both versions with compiler switches and compare results.

**Pull request closed without merging**
