### PR TITLE
new background grid and extended axis lines, fixes #1477

### LINKED ISSUE #1477: Add More Background Grids.
I got this feedback from one of my colleagues; and I felt it too in the beginning that the background grid is not that impressive. Please add the one like AutoCAD.

Version: 2.2.0-rc3
Compiler: GNU GCC 7.3.0
Compiled on: Nov 29 2021
Qt Version: 5.12.4
Boost Version: 1.65.1
System: Windows 10 (10.0)

### PR DESCRIPTION
**Pull request by melwyncarlo**
* Solved issue #1477
* Created a new lines-based grid (mimicking AutoCAD)
* Provided option to switch grids
* Extended axis lines
* Provided option to extend axis lines

<hr>

Video link : [https://youtu.be/hXNN_yvUyjs](https://youtu.be/hXNN_yvUyjs)

<hr>

Mimicking_AutoCAD_Background_Grid

### CODE REVIEW

**Comment by jbergengh** [comment]
Those look nice!

**Comment by melwyncarlo** [comment]
@jbergengh Thank you very much! :smiley: 

No, I had submitted a completed work; or so I thought.
When I reformatted the `include` headers, I got rid of `#include <iostream>`, thinking

**Comment by ajk2196** [comment]
Thank you @melwyncarlo . You are a blessing! Hats off your dedication.

**Comment by melwyncarlo** [comment]
Thank you very much, @ajk2196 ! :smiley:

**Comment by app4soft** [comment]
@lordofbikes, could be it resolved and merged to  _LibreCAD_ `2.2.2-alpha` branch?

**Comment by dxli** [comment]
Need to review for isometric also

**Comment by dxli** [comment]
I have tested this MR. More work needed:

1. Isometric grid support;
2. Preferences GUI needs some logic fixes;
3. I found the grid lines quite confusing. Need to reevaluate this feature design.

**Comment by dxli** [comment]
The same MR with merge conditions resolved: MR #1831

**Comment by app4soft** [comment]
### AutoCAD-like Grid Style in LibreCAD

Screenshot_2024-09-01_03-39-44

In "Application Preferences > Appearance" set:

- Background: `#212830`
- Grid Color: `#272d38`
- Metagrid Color: `#323848`
- Highlighted Color: `#ffffff`
- Preview Selectable Refernce Entity Color: `#ffffff`
- Preview Refernce Points: `+`
- Point Size: `8` Screen %
- [uncheck] Snap indicator line
- [uncheck] Snap indicator shape
- 
In "Current Drawing Preferences" set:

- Grid type: Lines
- Points: `□`
- Point Size: `3` Screen %

(Don't know how to set cursor shape as hollow square, or is such feature merged/implemented in latest LibreCAD `2.2.2_alpha`)

**Comment by dxli** [comment]
PR #1831 is the rebased version of this one. Let's close the outdated one

**Pull request closed without merging**
