### PR TITLE
LibreCAD Auto-Pan Function

### PR DESCRIPTION
**Pull request by melwyncarlo**
Auto-panning the CAD area:

Just place your mouse cursor near one of the CAD area borders and watch the CAD area pan automatically in the pointed direction. The closer the cursor is to the borders, the faster it will pan.

<hr>

Video link :  [https://youtu.be/0x3C5NNQj3Q](https://youtu.be/0x3C5NNQj3Q)

### CODE REVIEW

**Comment by dellus** [comment]
I am not sure I would like the screen content to move without my explicit wish. I might experience this a nervous behaviour.
Can we have it as an option?

**Comment by melwyncarlo** [comment]
Done!

**Comment by dellus** [comment]
Thanks a lot, melwyincarlo!
Oh so many checkboxes to have in mind...

**Comment by luzpaz** [comment]
It's great that this is an option. Any ETA on merge ?

**Comment by dongxuli-concord-design** [comment]
I will give it a try: review, (test, cleanup).

**Comment by u2fly** [comment]
@melwyncarlo, could You also add "**Auto-panning speed (px/second)** : `{value}`" to control the speed?

Screenshot_2023-06-20_21-12-47

**Pull request closed without merging**
