### PR TITLE
show current block in status bar, alternative to #1431, fixes #1333

### LINKED ISSUE #1333: Feature Request: Display Name of selected Block in Status Line
Hi,
i think it would be useful, if the Status Line would display the name of a block, if it gets selected.
I have projects with many blocks with nearly the same name. But i cannot identify, which of them i am currently selecting.
Or do i miss some documentation, where this is described?

Thank you and keep up the good work, which helps me greatly planning my house 👍 

Wolfgang

### PR DESCRIPTION
**Pull request by melwyncarlo**
* Solved issue #1333, differently

<hr>

Block_Name_in_Status_Bar

### CODE REVIEW

**Comment by jbergengh** [comment]
I'd really like to test this but I can't get it to compile.  I'm probably doing something stupid because I don't know how to use git very well.  I downloaded LibreCAD-Task_36.zip.  Then the usual qmake -qt=5 -r, and make -j4.  The compile ends with:

make[2]:` *** No rule to make target 'ui/forms/qg_selectionwidget.ui', needed by '../../generated/librecad/ui/ui_qg_selectionwidget.h'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/joel/Downloads/LibreCAD-Task_36/librecad/src'
make[1]: *** [Makefile:47: sub-src-make_first] Error 2
make[1]: Leaving directory '/home/joel/Downloads/LibreCAD-Task_36/librecad'
make: *** [Makefile:93: sub-librecad-make_first-ordered] Error 2

**Comment by melwyncarlo** [comment]
@jbergengh  No, you weren't doing anything wrong. I'm sorry, I forgot to change a UI file's name, and also I forgot to define an enumeration in a header file. Both are done now, and I've tested Task_36 separately. It should definitely work now.

**Comment by jbergengh** [comment]
@melwyncarlo thanks, it compiles now.
Tested and found a couple issues.
If I select a block in the drawing, wait a few seconds, then hit ESC to de-select all, the "Selected" count does not return to zero.  The count gets stuck and does not update until another block is selected.
Selecting two or more blocks in succession breaks the "Selected" and "Total Length" items by replacing them with a combined "Block Name" item that never goes away.

I think there is a much simpler way to implement this for you to consider.  How about this?

Whenever the user clicks on a block, display the block's name instead of the number of selected entities under the "Selected" item.  Don't bother pausing or anything.  Just leave the name there until they pick something else or hit ESC.  If they don't select a block, it's back to displaying the number of selected entities as normal.

**Comment by jbergengh** [comment]
@melwyncarlo Tested and working perfectly here.  I like it a lot.  Two thumbs up!

**Comment by melwyncarlo** [comment]
@jbergengh Thank you very much! :smiley:

**Pull request closed without merging**
