### PR TITLE
- fix #1098 Add a preference to allow whitespace in command interface

### LINKED ISSUE #1098: Add a preference to allow whitespace in command interface
As an EU of the LibreCAD command interface, I prefer the old 2.1.3 method which allowed me to use white space in my commands.

### Expected behavior

I can use white space.

### Observed behavior

Typing a space causes immediate evaluation before I was ready.

### Steps to reproduce or sample file

Use LibreCAD 2.2 rc1

### Operating System and LibreCAD version info

Win10, built from master, using Qt5.12.3/MinGW7.3, also Visual Studio 2017

This behavior was added for Issue #764.  It appears to have been designed to mimic AutoCAD functionality.  This should probably have a preference; I think it will be confusing for new users who are inexperienced with AutoCAD,

### PR DESCRIPTION
**Pull request by shawncurry**
- add new preference to allow whitespace in the command interface (the 2.1.3 behavior)
- add new checkable button to command interface popup menu to toggle the pref
- check the pref before interpreting space as eval trigger

### CODE REVIEW

**Comment by shawncurry** [comment]
TODO:

- Submit caption for review
- Translation

**Comment by shawncurry** [comment]
allowwhitespace

**Comment by shawncurry** [comment]
I defaulted it to true, by the way; preserving the 2.1.3 behavior.  Must be toggled to enable #764.

**Comment by vwren** [comment]
Just an observation for a minor tweak: I think the function would be more clear if the checkbox indicated what the whitespace was actually doing.  Keep the same default, but flip the meaning, because what you're really selecting is "Space Enters Data" (default is false).

To me, unchecking "Allow Whitespace" suggests that you simply can't put any spaces in, i.e. space is blocked, not that the space bar actually does something.

**Comment by shawncurry** [comment]
> Just an observation for a minor tweak: I think the function would be more clear if the checkbox indicated what the whitespace was actually doing. Keep the same default, but flip the meaning, because what you're really selecting is "Space Enters Data" (default is false).
> 
> To me, unchecking "Allow Whitespace" suggests that you simply can't put any spaces in, i.e. space is blocked, not that the space bar actually does something.

Thanks vwren.  I'm in total agreement about flipping the meaning.  It's what I wanted to do in the first place, but I couldn't think of a good way to word it.  I considered things like "Spacebar accepts commands" (from the title of #764) but I could just imagine someone in another country reading the translation and then trying to speak into their keyboard - lol.

**Comment by fa201** [comment]
"One may validate the entered command by pressing RETURN or SPACE BAR" ?

**Comment by shawncurry** [comment]
> "One may validate the entered command by pressing RETURN or SPACE BAR" ?

Looks like a winner 👍 lol

toolong

**Comment by shawncurry** [comment]
That reminded me though, about the other part that made it difficult.  We got about 4 words to describe it before all The Title Case Starts Looking Funny.  

That's another thing my tech writer will be hassling me about.  Proper titles only, everything else gets sentence case.  I guess this sort of thing is the reason.

- SPACE Evaluation
- Evaluate on SPACE
- SPACE Accepts My Commands
- Accept Commands on SPACE
- Can You Hear Me Major Tom
- Enter Commands on SPACE

I'm drawing a blank here guys.

**Comment by shawncurry** [comment]
Evaluate when SPACE BAR is pressed

That one seems great to me.  I'm taking the rest of the buttons to sentence case.  What do you think?

sentence

**Comment by lordofbikes** [comment]
In the [forum thread](http://forum.librecad.org/Do-you-use-the-cal-command-tp5713782p5713938.html) mentioned in #764, is this too:
> Also note that space-bar will toggle free snap when the cmd line is empty;
this is intended to help with placing dimensions. 

This is hard coded and puzzled users too, because SPACE BAR is used to activate the command line also.
Users who are used to use SPACE BAR for command line activation were annoyed by this unrelated toggling action.
So having an option for this too would be great, default is off.

Both options are not intended to be toggled all the time. I think users who use these options will stay with them and are aware of the consequences.
What do you think about moving them into the application preferences:
grafik
We can add a new group box *Keyboard settings* for these options.
This will also give more place for comprehensive check box labels.
Example code: #1087 added a check box to application preferences recently.

**Comment by shawncurry** [comment]
Hi Armin,

You are right, this setting would likely not be one that ever needs toggling once the user has chosen their preference.  The Application Preferences were the first place I went to look for this setting. That is a better place for it. 

I guess maybe I didn’t want to start thinking about that dialog yet. It seems likely that it will suffer from the “two column translation problem” I jokingly referenced earlier in this conversation.  The phrase “Modify layer of selected entities, at layer activation,” will almost certainly overrun its design length, and get cut off, when the translated phrase is substituted. 

This entire dialog should probably be redesigned to avoid these sorts of problems.

- Quick and dirty:  Give “Program Defaults” and “Startup” their own tab
- Better: reorganize the whole thing

Of course that problem deserves a ticket of its own. For now I’ll just find a place for it in Prefs.

**Comment by fa201** [comment]
My proposal was more documentation oriented, I agree it is too long. 
Regarding this command line validation, I admit this is very useful and efficient to activate and validate with <space> but I can understand that it is tricky for developers. The famous : one hand on mouse and one hand on keyboard for light fast inputs !!!
Would it be acceptable from coding perspective to have exclusive options : if <space> activates the command line then another letter / letter combination can validate ?
This should exclude automatically commands and 2-letter keycode. Keep in mind that <shift> also activate command line.
I like very much the idea of option panel defining these parameters !

**Comment by shawncurry** [comment]
prefs

See #1107 Create a preference to toggle Free Snap mode when SPACE BAR is pressed

**Comment by shawncurry** [comment]
I've added a fix for #1085 "Zoom panning can only be used once and must then be reactivated again"

**Pull request merged**
