### PR TITLE
refactor and refine RS_Debug

### PR DESCRIPTION
**Pull request by dpronin**
@dongxuli-concord-design check it out

I couldn't compile the project completely, unfortunately I managed to check only compilation of rs_debug.cpp

Is it possible for you to compile the project yourself and examine that rs_debug.o does not throw anything and not undergo a segmentation fault? I would appreciate if you checked

Thank you

### CODE REVIEW

**Comment by dpronin** [comment]
Finally, I succeeded in compiling and launching the project with these changes

**Comment by dpronin** [comment]
I ran the libreCAD at linux platform, gentoo distribution:

```bash
$ QT_QPA_PLATFORM=xcb ./unix/librecad -d 6
```

No issues are observed by mine, everything is logged out

**Comment by dxli** [comment]
I develop mainly on Gentoo with a little bit arch. For building, we have CI using ubuntu-20.04 at GitHub.

What's the issue beyond switching to pImp? 

I personally prefer lean design in rs_debug.h

**Comment by dongxuli-concord-design** [comment]
What we really want is a log file for bug reporting and call stack for crashes. 

Are you interested in?

**Comment by dpronin** [comment]
> What we really want is a log file for bug reporting and call stack for crashes. 
> 
> Are you interested in? 

What am I interested in? What is wrong with my proposal?

**Comment by dpronin** [comment]
@dongxuli-concord-design will you accept the changes? PIMPL is required to support FILE* within classes aggregations, i.e. among fields. You left FILE* as a static variable of the compilation unit that is an ugly design of singleton

**Comment by dpronin** [comment]
@dongxuli-concord-design please, merge the PR if no questions are left, or close it unless you are a coward to show that you do not agree with something, and please tell a reason. Stop holding it down in an open state

**Pull request closed without merging**
