### PR TITLE
Fix spelling errors in russian translate

### PR DESCRIPTION
**Pull request by lksj**

### CODE REVIEW

**Comment by lordofbikes** [comment]
Do not merge this.

I'm out for a job and will add more information later.

**Comment by r-a-v-a-s** [comment]
We use http://translate.librecad.org/

**Comment by lksj** [comment]
You can use anything you like, but why do you have in the repository translation with spell errors?
Fix it, or remove.
It's a shame.

**Comment by r-a-v-a-s** [comment]
I'm not Russian... and there isn't anyone who is payed to check the spelling correctness of translations.

lordofbikes handles translation integration; 
and he is busy as already stated...

I was informing you of the proper interface for any future translations.

**Comment by lksj** [comment]
> I don't speak Russian... and there isn't anyone who is paid to verify the spelling correctness of translations. This repository is maintained by volunteers.

OMG...
I made a patch to fix spell errors. Is free. What else is needed?
However, you have rejected it.
This is your project, not mine.
I can not insist.

>I meant to inform you of the proper interface for any future translations.

This unnecessarily. It will be helpful if you would inform people on http://translate.librecad.org/
If you wish, you can transfer them to my patch. This may facilitate the work.
However, you decide.

**Comment by r-a-v-a-s** [comment]
Unfortunately accepting pull requests here causes merge conflicts with the translation server.

I haven't worked with this system,
but I think the translation server allows
for more people to contribute with less conflict.

**Comment by lordofbikes** [comment]
@lksj please, come back down.

Everything is okay with your pull request and your effort is highly appreciated.
It's my fault, that I couldn't take care about your pull request earlier.

There is only a small core team behind LibreCAD and we all do this in out spare time. So there is sometimes simply no spare time or some other tasks with higher priority. But now I'm ready to work on your concern.

As r-a-v-a-s already stated, commits to the translation folders cause troubles on the translation server and therefore I will find a manual way to keep your contribution.
Our translation procedure is well documented in our Wiki and [Translation Sub Forum](http://forum.librecad.org/LibreCAD-translate-f5710645.html), but sadly not in the source code. I will change this to avoid translation pull requests in future.

There are many other good reasons for our translation server and that's the way it works by now.
Now, that you know about that, you are warm invited to register an account on our translation server and keep on contributing to Russian localization.

Now it's up to you to decide :wink:

**Comment by lordofbikes** [comment]
I've manually added your changes to the translation server, a sync with the source code is in progress.
Les than 10 of your 31 changes could be applied, because the others are obsolete or already translated on the server.

The obsolete keyword in .ts files mark messages which are only kept for backup reasons, they are outdated and not longer used in the source code.

Many thanks again for contributing.

**Pull request closed without merging**
