### PR TITLE
add drawimage button

### PR DESCRIPTION
**Pull request by dwlcreat**

### CODE REVIEW

**Comment by lordofbikes** [comment]
From your first commit it was not obvious what this pull request is about and obvious it was not finished.
Now, with the new commits, I Think I see the idea behind your efforts.

Before you put more efforts into this, let me notice, that the chances for your pull request to get merged are minimal.

What you achieve with coding is already possible with LibreCAD.
There are also already electrical/electronic symbol libraries existent.
The LibreCAD way to do this is to create DXF blocks for each symbol, collect them in library folders and add them from the library browser.

Using the library browser is not more effort than what you achieve with a new set of specialized tool buttons.

**Comment by dwlcreat** [comment]
> From your first commit it was not obvious what this pull request is about and obvious it was not finished. Now, with the new commits, I Think I see the idea behind your efforts.
> 
> Before you put more efforts into this, let me notice, that the chances for your pull request to get merged are minimal.
> 
> What you achieve with coding is already possible with LibreCAD. There are also already electrical/electronic symbol libraries existent. The LibreCAD way to do this is to create DXF blocks for each symbol, collect them in library folders and add them from the library browser.
> 
> Using the library browser is not more effort than what you achieve with a new set of specialized tool buttons.

**Comment by dwlcreat** [comment]
> unmerged
sorry, i just want to push to my repository, the merge request is not my idea. I don't create this mr.

**Comment by dwlcreat** [comment]
> > From your first commit it was not obvious what this pull request is about and obvious it was not finished. Now, with the new commits, I Think I see the idea behind your efforts.
> > Before you put more efforts into this, let me notice, that the chances for your pull request to get merged are minimal.
> > What you achieve with coding is already possible with LibreCAD. There are also already electrical/electronic symbol libraries existent. The LibreCAD way to do this is to create DXF blocks for each symbol, collect them in library folders and add them from the library browser.
> > Using the library browser is not more effort than what you achieve with a new set of specialized tool buttons.
 and ,Thanks for the tip, do you are know about the merge request like create dxf blocks.

**Comment by lordofbikes** [comment]
> and ,Thanks for the tip, do you are know about the merge request like create dxf blocks.

Sorry, but I don't understand you're request.

**Pull request closed without merging**
