### PR TITLE
Handle fractional imperial dimensions

### PR DESCRIPTION
**Pull request by Sleet01**
Implementation for https://sourceforge.net/p/librecad/feature-requests/41/
Adds the ability to parse commands containing unit symbols.

The idea behind this implementation was to add a few new measurement specification parsing options based on the number of feature requests I found, and to make it possible (and not too difficult) to add further parsing options in the future as needed.

Accepted command patterns (Negative symbol "-" may precede measurement string):
1) DMS with required degree and optional minutes/seconds:
- Degrees: degree[s] | deg | [Dd] | ° <required, else not matched>
- Minutes: minute[s] | min | [Mm] | ' <optional>
- Seconds: second[s] | sec | [Ss] | " <optional>
2) Metric string containing meters, centimeters, millimeters:
- Meters: meter[s] | m <optional>
- centimeters: centimeter[s] | centi | cm <optional>
- millimeters: millimeter[s] | milli | mm <optional>
3) Imperial with rational inch parts, e.g. "11ft6-7/8in":
- Yards: yard[s] | yd <optional>
- Feet: feet | foot | ft | ' <optional>
- Inches: inches | inch | in | " <optional>
-- Rational inch part: [-+]NN/DD <optional, must precede unit symbol>

Provisos:
1) Arithmetic operators are not allowed within measurements containing unit symbols (parsing would be too complex).
2) DMS, Metric, and Imperial measurement unit symbols may not be combined or mixed.
3) If no unit symbols are used, assumes the command is using default units for the GUI.
3) If no unit symbol is provided, or none of the above patterns match, the original command will be passed through to p.eval() unchanged, possibly causing syntax errors.
3) Currently there is no unit testing of the new functions.

I would like to add some basic unit tests so that future changes to the regex or logic can be vetted, but I'm not sure how to run the existing tests.  Is QT Creator required?

Many thanks!

### CODE REVIEW

**Comment by dellus** [comment]
Missing proper imperial architectural input has always been an issue and reason for complaints, as recently: https://forum.librecad.org/Units-displayed-when-inserting-dimensions-tp5718204.html
So I have investigated how it's handled in AutoCAD. Quote from AutoCAD 2009 User's Guide:

Enter Distances in Imperial Architectural Format
In architectural format, to enter feet and inches, indicate feet using the prime
symbol ('), for example, 72'3. You don't need to enter quotation marks (“) to
specify inches.  

I don't have access to AutoCAD, but have tested it with NanoCAD 5, which is available for free and claims to stick to AutoCAD conventions. It works there. I think it's worth considering to be compatible. Does your model support this?

**Comment by Sleet01** [comment]
> Missing proper imperial architectural input has always been an issue and reason for complaints, as recently: https://forum.librecad.org/Units-displayed-when-inserting-dimensions-tp5718204.html
> So I have investigated how it's handled in AutoCAD. Quote from AutoCAD 2009 User's Guide:
> 
> Enter Distances in Imperial Architectural Format
> In architectural format, to enter feet and inches, indicate feet using the prime
> symbol ('), for example, 72'3. You don't need to enter quotation marks (“) to
> specify inches.
> 
> I don't have access to AutoCAD, but have tested it with NanoCAD 5, which is available for free and claims to stick to AutoCAD conventions. It works there. I think it's worth considering to be compatible. Does your model support this?

It does not currently, but it would be simple enough to make the inch (") mark optional when the foot mark (') is detected.  I'll write that up tomorrow.

**Comment by clayreimann** [comment]
Any updates on this? Even without the optional `"` I think that this should be merged!

**Comment by Sleet01** [comment]
> Any updates on this? Even without the optional `"` I think that this should be merged!

Sorry, I haven't worked on this in a bit.  Let me poke around and see if I got far enough to wrap it all up.

**Comment by atorrey** [comment]
Another dimensioning option that I'd like is to have 'dual dimensions' so that you can have both imperial and metric dimensions on the same drawing (i.e. '1.0" (25.4mm)' or similar)

This would be really useful for drawings that will be shared so that they are useful regardless of what the viewers preferred system is.  I see it frequently on drawings I download from commercial sites.

It is also useful when doing things like trying to make a metric dimensioned part on an older CNC machine that is easier to program in imperial or vice versa...

------------------
Arthur Torrey - ***@***.***>
-------------------

**Comment by dellus** [comment]
In 2.2.1-alpha-125 now if if you draw a dimension on a 100 feet length in architectural mode it reads 3 -15/16" instead of 8' - 4".
Seems a case of inches - mm confusion, factor 25.4 .

**Comment by GSStnb** [comment]
"...a 100 feet length..." I suspect you meant 100 inches(?)  If it is 100 feet, that would be a bigger problem.

**Comment by dellus** [comment]
Sorry, yes of course I meant 100 inches.

**Pull request merged**
