### PR TITLE
Enhance visibility of black lines on dark backgrounds

### PR DESCRIPTION
**Pull request by JeremyRuhland**
Implementing functionality proposed in #1256 
Program compiled and tested as working.

### CODE REVIEW

**Comment by dellus** [comment]
If someone deliberately wants to use white lines or white solid hatches, for instance above an other coloured area, or to hide parts of a drawing with a white cover, this is prevented by the automatic black / white swap. Up to now there is the work around to use a slightly off nearly white, like RGB 255,255,254.
The fuzzy colour filter you propose prohibits this, doesn't it?

**Comment by JeremyRuhland** [comment]
I'm not sure I fully understand the situation you're describing. The fuzzy filter only affects lines set to black (it's kind of confusing nomenclature that black and white are the same color internally).
The work around you describe would still function as intended.

On July 6, 2020 2:17:45 PM PDT, dellus <notifications@github.com> wrote:
>If someone deliberately wants to use white lines or white solid
>hatches, for instance above an other coloured area, or to hide parts of
>a drawing with a white cover, this is prevented by the automatic black
>/ white swap. Up to now there is the work around to use a slightly off
>nearly white, like RGB 255,255,254.
>The fuzzy colour filter you propose prohibits this, doesn't it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibreCAD/LibreCAD/pull/1257#issuecomment-654470257

-- 

Jeremy Ruhland
jeremy@goopypanther.org

**Comment by dellus** [comment]
Ok, I have got it wrong. So my issue is a different topic.
Just for your interest, to clear what I was talking about, a sample file and how it should look printed:

[offwhitesample.zip](https://github.com/LibreCAD/LibreCAD/files/4884696/offwhitesample.zip)

**Comment by lordofbikes** [comment]
Many thanks!

**Pull request merged**
