### PR TITLE
sanitize

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by r-a-v-a-s** [comment]
For the system to properly credit you: 
make sure your github account's email and the one set with git are the same
(note the tooltip of the '?' icon next to your name in the commit).

https://help.github.com/articles/setting-your-email-in-git/

Thanks for your effort.

**Comment by rbuj** [comment]
Done

**Comment by rbuj** [comment]
sudo port -qsc install muparser boost qt5
cd LibreCAD/scripts
./build-osx.sh -qmake_opts="QMAKE_MAC_SDK=macosx10.11"
https://dl.dropboxusercontent.com/u/242984/LibreCAD.dmg

**Comment by r-a-v-a-s** [comment]
:sunglasses: 

I'll merge it tomorrow if no one comments.

You can close the other pull request if this contains the same commit.

**Comment by rbuj** [comment]
OK

**Pull request merged**
