### PR TITLE
Pen toolbar - sync pen by layer action now works if PenPalette widget is disabled

### PR DESCRIPTION
**Pull request by sand1024**
Original implementation relied on PenPalette widget for applying active layer's pen to pen toolbar, so if PenPalette is disabled - that action didn't work. 
Now separate action was added, so functionality is restored and works if PenPalette is disabled.

### CODE REVIEW

**Comment by dongxuli-concord-design** [comment]
Hi @sand1024

Did you do something to reduce the sizes?

**Comment by sand1024** [comment]
Hi!
not yet, I'm going to start adjusting sizes now and hope I'll commit them in nearest couple of days. 

That commit is for a bit different situation - previously, the action for updating pen by layer's pen used invocation of method from PenPalette - and so that was the reason why the action (2 green triangles) was not executed if PenPalette is disabled. 

Now I've added separate action, so PenToolBar and PenPalette are independent.

**Comment by sand1024** [comment]
I think I'll fix "By Layer" issue in properties first (#1759) as it is faster, and after it will switch to sizes adjustments.

**Comment by sand1024** [comment]
committed fix for #1759

**Pull request merged**
