### PR TITLE
restructure main project file

### PR DESCRIPTION
**Pull request by webmite**
restructure main project file to show project structure and
represent the project dependencies.

used this link as a guide.
https://wiki.qt.io/SUBDIRS_-_handling_dependencies

### CODE REVIEW

**Comment by webmite** [comment]
I am now on a ubuntu 16.04 platform for development.  Microsoft win10 ate my previous laptop platform. I had to make the above changes to the project file in order to get Qt to Build successfully.

**Comment by lordofbikes** [comment]
I refuse this pull request.

This line cares for the correct build order of the subdirs listed there, libraries first, then the app:
https://github.com/LibreCAD/LibreCAD/blob/0715edc7d8082087d172c4bc822186eecd9c9e67/librecad.pro#L3

I haven't tested your modification, but it seems to create a kind of recursion. The libraries subprojects are used twice then, in [/librecad.pro](https://github.com/LibreCAD/LibreCAD/blob/0715edc7d8082087d172c4bc822186eecd9c9e67/librecad.pro) and in modified [/librecad/librecad.pro](https://github.com/webmite/LibreCAD/blob/a130b19a6e7cfd2a907b75009ac772938c2d709c/librecad/librecad.pro). I don't know, what qmake create from this settings.

I have no issues on Ubuntu 16.04 with current project files. Thus if it doesn't build on your system, there must be another, system specific problem.

If you still have issues with current project files, you can share error logs, the steps how you build and your Qt and GCC versions.

**Comment by webmite** [comment]
Thanks for the explanation.  It would appear that for whatever reason I failed to see /librecad.pro on my local distribution and have been doing all compiles only against the subproject file /librecad/librecad.pro .. My apologies.  That explains why it appears recursive to you.  My mistake.

I will compile against the top-level and confirm all settings myself.

**Comment by lordofbikes** [comment]
Don't worry, your efforts are more than welcome.
I hope it works for you now.

**Pull request closed without merging**
