### PR TITLE
Fix Ukrainian characters LFF markup in unicode.lff

### PR DESCRIPTION
**Pull request by Symbian9**
See https://github.com/LibreCAD/LibreCAD/issues/690#issuecomment-206942438

### CODE REVIEW

**Comment by phkahler** [comment]
@Symbian9  Why the removal of 0406 and 0456 and 0457?  I'm not sure removing glyphs is a good idea.  It also looks like some glyphs were in the original file twice, is that correct? I'm also curious about the changes making a multi-line entry from a single-line one without any visible change. Did a tool do that automatically?

I'm not sure why, but I'm stuck on this idea of having the two projects use the exact same version of this font ;-)

**Comment by Symbian9** [comment]
>  Why the removal of 0406 and 0456 and 0457?

@phkahler, I'm not removed it!

I just removed duplicates of *raw code* & left only *reference link to similar character* instead.

**Comment by Symbian9** [comment]
@lordofbikes, please, merge this and https://github.com/LibreCAD/LibreCAD/pull/1365 which are just brings few fixes & additions to `unicode.lff` font.

**Comment by Symbian9** [comment]
@lordofbikes, any news on this pull merging status?

**Comment by lordofbikes** [comment]
@Symbian9 focus is currently on final release of 2.2.0.
The build systems are revamped to create all needed packages for Windows, MacOS and Linux.
Before the final release I'll check all pull request and merge what is safe without impacting stability.

**Comment by lordofbikes** [comment]
Many thanks!

**Pull request merged**
