### PR TITLE
Committer: Equoda <Equoda@users.noreply.github.com>

### LINKED ISSUE #715: Can't move a number of blocks
Can't "Move" a number of blocks, copied from another draft.

Steps to reproduce:

1. Create new draft
2. Create a shape ("Rectangle")
3. Create a block from shape ("Create Block -> $block_name")
4. Repeat 2. and 3. (I created 3 blocks)
5. Select all, "Edit -> Copy"
6. Create new draft
7. "Edit -> Paste"
8. Select all, "Move (delete original)"

Result: some shapes disappears.

Librecad info:

Version: 2.1.0-beta
Tag: 2.1.0-beta-8-g9723828
Compiler: GNU GCC 4.8.4
Compiled on: May 16 2016
Qt Version: 4.8.6
Boost Version: 1.54.0

Drafts are created from templates. Here is an example of draft with shapes: 
[blocks.dxf.zip](https://github.com/LibreCAD/LibreCAD/files/265934/blocks.dxf.zip)

### PR DESCRIPTION
**Pull request by Equoda**
fix: blocks moving/pasting bug

Solve the problem with copy-paste or move blocks bug cause some blocks disappears.
Most changes are in ```librecad/src/lib/modification/rs_modification.cpp```.
```RS_Modification::paste``` function has been rewritten.

Closes #715

### CODE REVIEW

**Comment by r-a-v-a-s** [comment]
I don't see anything negligent;
I'll merge these later today if no one else comments.

**Comment by r-a-v-a-s** [comment]
Here's a quick fix for the crash:
1. ctrl+c
2. ctrl+v
3. click in drawing area

https://github.com/LibreCAD/LibreCAD/commit/954d57fedd660b230a296b5f36ac45ef5c351f6c

**Comment by Equoda** [comment]
Sorry, my fault! I was too pythonic.

**Comment by r-a-v-a-s** [comment]
Considering it only crashed when using improper procedure, I don't think you were negligent. :-]
In fact your work is commendable.

**Pull request merged**
