### PR TITLE
Merge pull request #1 from LibreCAD/master

### PR DESCRIPTION
**Pull request by Joeycc**
11

### CODE REVIEW

**Comment by Joeycc** [comment]
fd

**Comment by Joeycc** [comment]
11

**Comment by r-a-v-a-s** [comment]
😮

**Comment by r-a-v-a-s** [comment]
If you were trying to sync your fork:
https://help.github.com/articles/syncing-a-fork/

https://github.com/LibreCAD/LibreCAD/wiki/Git-and-GitHub

**Pull request closed without merging**
