### PR TITLE
added layer/block selection color option

### PR DESCRIPTION
**Pull request by r-a-v-a-s**
The `.ui` file shows a lot of changes,
but this was mostly an automatic update.
I had to break the grid layout and then reapply it to fix a bug.
I'm guessing Qt has tweaked the grid layout since it was first applied in our program.

### CODE REVIEW

**Comment by dxli** [comment]
wondering whether we can add http://doc.qt.io/qt-4.8/qcolordialog.html to select colors.

**Comment by lordofbikes** [comment]
QColorDialog was recently implemented by ravas for *Application Preferences*, see commit 08fe8f132ca7b22ff34cf7d6674bbbf813e948bd / #542

**Comment by r-a-v-a-s** [comment]
I used the same `set_color` function, which uses the QColorDialog.

The change to the `.ui` can be seen at the bottom of the color section.

appearance

**Comment by r-a-v-a-s** [comment]
If no problems are noted, then I will merge my requests after 24 hours.
To reduce this time reviewers can comment: "No problems noticed."
To increase this time reviewers can state when they plan on reviewing.

**Comment by dxli** [comment]
I don't see any problem here.

**Pull request merged**
