### PR TITLE
Improving rendering performance w.r.t. #727

### PR DESCRIPTION
**Pull request by rubdos**
As stated in issue #727, using a lot of entities makes LibreCAD slow. I'm trying to figure out what things can get optimized. I already have one commit which makes it noticeably faster.

~~**Please do not merge yet, I'm going to find more optimizations.**~~

### CODE REVIEW

**Comment by rubdos** [comment]
Let's say that I cannot find more bottlenecks that are easy to tackle. There's still one that could use investigation: 6% of the drawing time of the dxf file in #727 goes to `RS_EntityContainers::clear()`, which is called by `RS_EntityContainer::~RS_EntityContainer()`.

This sits so deep that I do not dare to touch it though, so perhaps someone else could look at that. 

The EntityContainer's in question are those of `RS_Line::draw()`, which uses one to calculate some intersections before getting disposed. I assume that that part can be optimized easily, although someone could have a look at the mentioned clear() method too.

**Comment by rubdos** [comment]
@r-a-v-a-s, why do you think my git email isn't set right?

```
git config --global -l
user.email=ruben.de.smet [at] rubdos.be
user.name=Ruben De Smet
```
(the [at] is against crappy spambots, but it's right in my config. Just replaced it here)

Iirc, github has that e-mail address registered. Perhaps not as primary, but they know about it :P

**Comment by r-a-v-a-s** [comment]
See the '?' next to your name in the commit.

You have merged commits, yet you are not in the contributors list.

**Comment by rubdos** [comment]
Oooh, okay, that's more logical now. GitHub knows about that e-mail address now. I recently bought that domain, but I only added it on GitLab, not here.

**Pull request merged**
